<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_loginpassword</name>
   <tag></tag>
   <elementGuidId>1842b210-e060-4096-90c7-f48a1cfc9537</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#loginpassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='loginpassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>738caa60-f87c-42af-923b-e05665f38998</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>3014034b-2fce-45fe-853d-c57e39979915</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ab938d4c-cf68-4ce6-9bd8-2f4de4401eac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>loginpassword</value>
      <webElementGuid>681e4aa6-769a-46e1-a422-f34ac0a1b56e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginpassword&quot;)</value>
      <webElementGuid>6e8eccda-4a23-4daa-9c36-0fdc87ddec15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='loginpassword']</value>
      <webElementGuid>c17ab93f-e017-4db9-83eb-58b34d94cb93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='logInModal']/div/div/div[2]/form/div[2]/input</value>
      <webElementGuid>04af43d8-f57e-4f42-8a0f-0d61441a897e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/form/div[2]/input</value>
      <webElementGuid>3fc27239-b3ee-4bf0-a3ab-43ba97d9480d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'loginpassword']</value>
      <webElementGuid>4b4e2881-b117-4ef4-afd8-d6571af63bfd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
